import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar";
import ParticleComponent from "@/components/particle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tubes Stima 2 - DEBDOB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{backgroundColor: '#EEEEEE'}}>
        <ParticleComponent />
        <div className="fixed w-full z-50">
          <Navbar />
        </div>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
